#spirng.profiles.active=dev

server:
  port: 8080
  contextPath: /

logging:
  file: D:\\weixiuhui_upload\\log.log
  level:
    org.spirngframework.web: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    showSql: true
    hibernate:
      #使用hibernate来自动更新表结构，不存在即创建，修改了表结构，在程序启动时，同步更新数据库表结构
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

# gRPC有关的配置，这里只需要配置服务端口号
grpc:
  server:
    port: 9898
  client:
    # gRPC配置的名字，GrpcClient注解会用到
    local-grpc-server:
      # gRPC 本地服务端地址 也可注册中心
      address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
