server:
  port: 8080

spring:
  devtools:
    restart:
      enable: false
  redis:
    host: 192.168.1.24
    port: 6381
    password:
    ssl: false
    jedis:
      pool:
        max-idle: 10
        max-wait: 60000
redis:
  channel:
    msgToAll: webscoker.msgToAll
    noticeToAll: webscoker.noticeToAll

socketio:
  host: localhost
  port: 9092
  boss-threads: 1
  worker-threads: 100
  is-allow-custom-requests: true
  upgrade-timeout: 1000000
  ping-timeout: 5000000
  ping-interval: 30000

