/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_peng_studygodpath_java8_sourcecode_JNI_JNITry */

#ifndef _Included_cn_peng_studygodpath_java8_sourcecode_JNI_JNITry
#define _Included_cn_peng_studygodpath_java8_sourcecode_JNI_JNITry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_peng_studygodpath_java8_sourcecode_JNI_JNITry
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_peng_studygodpath_java8_sourcecode_JNI_JNITry_hello
  (JNIEnv *, jclass);

/*
 * Class:     cn_peng_studygodpath_java8_sourcecode_JNI_JNITry
 * Method:    add
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_cn_peng_studygodpath_java8_sourcecode_JNI_JNITry_add
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
